### ISSUE TITLE
Security Disclosure Wiki 

### ISSUE THREAD

**Issue by ghost** [UCF/Campus-Map#6]
I decided to create wiki addressing one of the vulnerabilities that was patched within Campus Map. I can have the second one documented once it's been patched. Overall, I'd like to be able to have any bug disclosures I've made at UCF publicly indexed via the web to serve as a bug tracking catalog for myself and to others who wish to do the same.Please let me know what you think and how you would like to go about making this accessible.

**Comment by fl0kii** [comment]
???

**Comment by jmbarne3** [comment]
Feel free to link back and publish all you want. For future vulnerabilities, however, I would ask that you either submit a pull request with the changes before referencing them elsewhere, or else at least contact us and let us know so we can put it in the backlog or open an issue.
